a = [
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Equipes de Saúde da Família - eSF e equipes de Atenção Primária - eAP",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 10140000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 10140000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Equipes de Saúde da Família - eSF e equipes de Atenção Primária - eAP",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 10092000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 10092000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Equipes de Saúde da Família - eSF e equipes de Atenção Primária - eAP",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 10048200,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 10048200,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Equipes de Saúde da Família - eSF e equipes de Atenção Primária - eAP",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 9966900,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 9966900,
      "vlImplantacao": 120000,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 120000
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Equipes de Saúde da Família - eSF e equipes de Atenção Primária - eAP",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 9957000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 9957000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Atenção à Saúde Bucal",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 2130927.65,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 2130927.65,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Atenção à Saúde Bucal",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 2101673.9,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 2101673.9,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Atenção à Saúde Bucal",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 2076083.65,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 2076083.65,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Atenção à Saúde Bucal",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 2087785.15,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 2087785.15,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Atenção à Saúde Bucal",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 2103510.65,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 2103510.65,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Equipes Multiprofissionais - eMulti",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Equipes Multiprofissionais - eMulti",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Equipes Multiprofissionais - eMulti",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Equipes Multiprofissionais - eMulti",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 185250,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 185250,
      "vlImplantacao": 156000,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 156000
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Equipes Multiprofissionais - eMulti",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 185250,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 185250,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Agentes Comunitários de Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 3894296,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 3894296,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Agentes Comunitários de Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 3885824,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 3885824,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Agentes Comunitários de Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 3812400,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 3812400,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Agentes Comunitários de Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 3699440,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 3699440,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Agentes Comunitários de Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 3702264,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 3702264,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "ESTADUAL",
      "vlIntegral": 30000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 30000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 391986.5,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 391986.5,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "ESTADUAL",
      "vlIntegral": 30000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 30000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 394986.5,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 394986.5,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "ESTADUAL",
      "vlIntegral": 30000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 30000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 405681.5,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 405681.5,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "ESTADUAL",
      "vlIntegral": 30000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 30000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 388986.5,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 388986.5,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "ESTADUAL",
      "vlIntegral": 91000,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 91000,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Demais programas, serviços e equipes da Atenção Primária à Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 379986.5,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 379986.5,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Manutenção de pagamento de valor nominal com base em exercício anterior",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 1438074.84,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 1438074.84,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202404",
      "nuParcela": "202406",
      "dsPlanoOrcamentario": "Manutenção de pagamento de valor nominal com base em exercício anterior",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 1438074.84,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 1438074.84,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Manutenção de pagamento de valor nominal com base em exercício anterior",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 1438074.84,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 1438074.84,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202406",
      "nuParcela": "202408",
      "dsPlanoOrcamentario": "Manutenção de pagamento de valor nominal com base em exercício anterior",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 1438074.84,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 1438074.84,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Manutenção de pagamento de valor nominal com base em exercício anterior",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 1438074.84,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 1438074.84,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202403",
      "nuParcela": "202405",
      "dsPlanoOrcamentario": "Academia da Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202405",
      "nuParcela": "202407",
      "dsPlanoOrcamentario": "Academia da Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    },
    {
      "sgUf": "BA",
      "coUfIbge": "29",
      "coMunicipioIbge": "292740",
      "noMunicipio": "SALVADOR",
      "nuCompCnes": "202407",
      "nuParcela": "202409",
      "dsPlanoOrcamentario": "Academia da Saúde",
      "dsEsferaAdministrativa": "MUNICIPAL",
      "vlIntegral": 0,
      "vlAjuste": 0,
      "vlDesconto": 0,
      "vlEfetivoRepasse": 0,
      "vlImplantacao": 0,
      "vlAjusteImplantacao": 0,
      "vlDescontoImplantacao": 0,
      "vlTotalImplantacao": 0
    }
]
console.log(a.length)